/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BytesLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  GameCommitRevaal,
  GameCommitRevaalInterface,
} from "../../../../../contracts/practice-GuideDAO/security/GameCommitReveal.sol/GameCommitRevaal";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_hashedSecretNumber",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "hashedSecretNumber",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_secretNumber",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_salt",
        type: "bytes32",
      },
    ],
    name: "reveal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f80fd5b506040516101e13803806101e1833981016040819052602b916032565b6001556048565b5f602082840312156041575f80fd5b5051919050565b61018c806100555f395ff3fe608060405234801561000f575f80fd5b5060043610610034575f3560e01c80633f9471aa146100385780634036778f14610053575b5f80fd5b61004160015481565b60405190815260200160405180910390f35b610066610061366004610136565b610068565b005b6040517fffffffffffffffffffffffffffffffffffffffff0000000000000000000000003360601b16602082015260348101839052605481018290525f906074016040516020818303038152906040528051906020012090506001548114610130576040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152600f60248201527f696e76616c69642072657665616c210000000000000000000000000000000000604482015260640160405180910390fd5b50505f55565b5f8060408385031215610147575f80fd5b5050803592602090910135915056fea26469706673582212203a98a4fb24f2c872c86fae761de49918ed1bd084a5c2fd02256b90483a1d062664736f6c634300081a0033";

type GameCommitRevaalConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GameCommitRevaalConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GameCommitRevaal__factory extends ContractFactory {
  constructor(...args: GameCommitRevaalConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _hashedSecretNumber: BytesLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_hashedSecretNumber, overrides || {});
  }
  override deploy(
    _hashedSecretNumber: BytesLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_hashedSecretNumber, overrides || {}) as Promise<
      GameCommitRevaal & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): GameCommitRevaal__factory {
    return super.connect(runner) as GameCommitRevaal__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GameCommitRevaalInterface {
    return new Interface(_abi) as GameCommitRevaalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): GameCommitRevaal {
    return new Contract(address, _abi, runner) as unknown as GameCommitRevaal;
  }
}
