/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  BooleanStorage,
  BooleanStorageInterface,
} from "../../../contracts/practice-junior/BooleanStorage";

const _abi = [
  {
    inputs: [],
    name: "get",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "x",
        type: "bool",
      },
    ],
    name: "set",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "storedBoolean",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f80fd5b5060fd8061001b5f395ff3fe6080604052348015600e575f80fd5b5060043610603a575f3560e01c80635c7ad84614603e5780635f76f6ab14605d5780636d4ce63c14609a575b5f80fd5b5f5460499060ff1681565b604051901515815260200160405180910390f35b6098606836600460a3565b5f80547fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0016911515919091179055565b005b5f5460ff166049565b5f6020828403121560b2575f80fd5b8135801515811460c0575f80fd5b939250505056fea2646970667358221220fb493b2a7b8dc861fdd2f074092d519747dfb1c900333b944bc67a5819899bd764736f6c634300081a0033";

type BooleanStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BooleanStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BooleanStorage__factory extends ContractFactory {
  constructor(...args: BooleanStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BooleanStorage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BooleanStorage__factory {
    return super.connect(runner) as BooleanStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BooleanStorageInterface {
    return new Interface(_abi) as BooleanStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BooleanStorage {
    return new Contract(address, _abi, runner) as unknown as BooleanStorage;
  }
}
