/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  CircularBuffer,
  CircularBufferInterface,
} from "../../../contracts/practice-junior/CircularBuffer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_size",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "add",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "idx",
        type: "uint256",
      },
    ],
    name: "get",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSize",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b5060405161038438038061038483398101604081905261002e91610133565b5f81116100745760405162461bcd60e51b815260206004820152601060248201526f053697a65206d757374206265203e20360841b604482015260640160405180910390fd5b806001600160401b0381111561008c5761008c61014a565b6040519080825280602002602001820160405280156100b5578160200160208202803683370190505b5080516100c9915f916020909101906100d6565b506001555f60025561015e565b828054828255905f5260205f2090810192821561010f579160200282015b8281111561010f5782518255916020019190600101906100f4565b5061011b92915061011f565b5090565b5b8082111561011b575f8155600101610120565b5f60208284031215610143575f80fd5b5051919050565b634e487b7160e01b5f52604160045260245ffd5b6102198061016b5f395ff3fe608060405234801561000f575f80fd5b506004361061003f575f3560e01c80631003e2d2146100435780639507d39a14610058578063de8fa4311461007d575b5f80fd5b610056610051366004610174565b610085565b005b61006b610066366004610174565b6100c8565b60405190815260200160405180910390f35b60015461006b565b805f6002548154811061009a5761009a61018b565b905f5260205f20018190555060015460025460016100b8919061019f565b6100c291906101c4565b60025550565b5f6001548210610138576040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152601360248201527f496e646578206f7574206f6620626f756e647300000000000000000000000000604482015260640160405180910390fd5b5f6001548360025461014a919061019f565b61015491906101c4565b815481106101645761016461018b565b905f5260205f2001549050919050565b5f60208284031215610184575f80fd5b5035919050565b634e487b7160e01b5f52603260045260245ffd5b808201808211156101be57634e487b7160e01b5f52601160045260245ffd5b92915050565b5f826101de57634e487b7160e01b5f52601260045260245ffd5b50069056fea2646970667358221220f34979887b933304600ba665db5dd92d5cd768a88c6b21a5367d5725fdbaeb3a64736f6c634300081a0033";

type CircularBufferConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CircularBufferConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CircularBuffer__factory extends ContractFactory {
  constructor(...args: CircularBufferConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _size: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_size, overrides || {});
  }
  override deploy(
    _size: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_size, overrides || {}) as Promise<
      CircularBuffer & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CircularBuffer__factory {
    return super.connect(runner) as CircularBuffer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CircularBufferInterface {
    return new Interface(_abi) as CircularBufferInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CircularBuffer {
    return new Contract(address, _abi, runner) as unknown as CircularBuffer;
  }
}
