/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as factorialSol from "./Factorial.sol";
export type { factorialSol };
import type * as receiveEtherSol from "./ReceiveEther.sol";
export type { receiveEtherSol };
export type { BaseContract } from "./BaseContract";
export type { DataConsumer } from "./DataConsumer";
export type { DataProvider } from "./DataProvider";
export type { EmployeeData } from "./EmployeeData";
export type { FallbackExample } from "./FallbackExample";
export type { InheritedContract } from "./InheritedContract";
export type { Library } from "./Library";
export type { NestedMappings } from "./NestedMappings";
export type { Power } from "./Power";
export type { ProductStore } from "./ProductStore";
export type { UserRegistry } from "./UserRegistry";
export type { VotingWithDelegation } from "./VotingWithDelegation";
