/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface UniqueCountInterface extends Interface {
  getFunction(
    nameOrSignature: "addUniqueValue" | "getUniqueCount" | "uniqueValues"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addUniqueValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUniqueCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniqueValues",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addUniqueValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUniqueCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniqueValues",
    data: BytesLike
  ): Result;
}

export interface UniqueCount extends BaseContract {
  connect(runner?: ContractRunner | null): UniqueCount;
  waitForDeployment(): Promise<this>;

  interface: UniqueCountInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addUniqueValue: TypedContractMethod<
    [value: BigNumberish],
    [void],
    "nonpayable"
  >;

  getUniqueCount: TypedContractMethod<[], [bigint], "view">;

  uniqueValues: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addUniqueValue"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getUniqueCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "uniqueValues"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  filters: {};
}
