/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ValidatorInterface extends Interface {
  getFunction(nameOrSignature: "validateParameters"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ParametersValidated"): EventFragment;

  encodeFunctionData(
    functionFragment: "validateParameters",
    values: [AddressLike, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "validateParameters",
    data: BytesLike
  ): Result;
}

export namespace ParametersValidatedEvent {
  export type InputTuple = [
    _address: AddressLike,
    _number: BigNumberish,
    _text: string
  ];
  export type OutputTuple = [_address: string, _number: bigint, _text: string];
  export interface OutputObject {
    _address: string;
    _number: bigint;
    _text: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Validator extends BaseContract {
  connect(runner?: ContractRunner | null): Validator;
  waitForDeployment(): Promise<this>;

  interface: ValidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  validateParameters: TypedContractMethod<
    [_address: AddressLike, _number: BigNumberish, _text: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "validateParameters"
  ): TypedContractMethod<
    [_address: AddressLike, _number: BigNumberish, _text: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ParametersValidated"
  ): TypedContractEvent<
    ParametersValidatedEvent.InputTuple,
    ParametersValidatedEvent.OutputTuple,
    ParametersValidatedEvent.OutputObject
  >;

  filters: {
    "ParametersValidated(address,uint256,string)": TypedContractEvent<
      ParametersValidatedEvent.InputTuple,
      ParametersValidatedEvent.OutputTuple,
      ParametersValidatedEvent.OutputObject
    >;
    ParametersValidated: TypedContractEvent<
      ParametersValidatedEvent.InputTuple,
      ParametersValidatedEvent.OutputTuple,
      ParametersValidatedEvent.OutputObject
    >;
  };
}
