/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as practiceGuideDao from "./PracticeGuideDAO";
export * as practiceJunior from "./PracticeJunior";
export * as practiceMiddle from "./PracticeMiddle";
export * as practiceModule1 from "./PracticeModule1";
export * as practiceModule2 from "./PracticeModule2";
