/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface TodosInterface extends Interface {
  getFunction(
    nameOrSignature: "create" | "todos" | "toggleCompleted" | "updateText"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "create", values: [string]): string;
  encodeFunctionData(functionFragment: "todos", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "toggleCompleted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateText",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "todos", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateText", data: BytesLike): Result;
}

export interface Todos extends BaseContract {
  connect(runner?: ContractRunner | null): Todos;
  waitForDeployment(): Promise<this>;

  interface: TodosInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  create: TypedContractMethod<[_text: string], [void], "nonpayable">;

  todos: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, boolean] & { text: string; completed: boolean }],
    "view"
  >;

  toggleCompleted: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateText: TypedContractMethod<
    [_index: BigNumberish, _text: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "create"
  ): TypedContractMethod<[_text: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "todos"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, boolean] & { text: string; completed: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "toggleCompleted"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateText"
  ): TypedContractMethod<
    [_index: BigNumberish, _text: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
