/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressRecord } from "./AddressRecord";
export type { Record } from "./Record";
export type { RecordFactory } from "./RecordFactory";
export type { StringRecord } from "./StringRecord";
