/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ArrayCount,
  ArrayCountInterface,
} from "../../../contracts/PracticeJunior/ArrayCount";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "number",
        type: "uint256",
      },
    ],
    name: "addNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "numbers",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f80fd5b506101098061001c5f395ff3fe6080604052348015600e575f80fd5b5060043610603a575f3560e01c8063a87d942c14603e578063d39fa233146053578063fce68023146062575b5f80fd5b5f545b60405190815260200160405180910390f35b6041605e36600460bd565b60a0565b609e606d36600460bd565b5f80546001810182559080527f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e5630155565b005b5f818154811060ad575f80fd5b5f91825260209091200154905081565b5f6020828403121560cc575f80fd5b503591905056fea2646970667358221220a1aa4556ec9b266df6cbcdb41612a6880f2662d2630b17fc0bd3780942af07a064736f6c634300081a0033";

type ArrayCountConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ArrayCountConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ArrayCount__factory extends ContractFactory {
  constructor(...args: ArrayCountConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ArrayCount & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ArrayCount__factory {
    return super.connect(runner) as ArrayCount__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ArrayCountInterface {
    return new Interface(_abi) as ArrayCountInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ArrayCount {
    return new Contract(address, _abi, runner) as unknown as ArrayCount;
  }
}
