/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MultiReturnExample,
  MultiReturnExampleInterface,
} from "../../../contracts/PracticeJunior/MultiReturnExample";

const _abi = [
  {
    inputs: [],
    name: "getValues",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f80fd5b5061010f8061001c5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c806319eb4a9014602a575b5f80fd5b604080518082018252601081527f48656c6c6f2c20536f6c6964697479210000000000000000000000000000000060208201529051606d91602a91600191906076565b60405180910390f35b8381528215156020820152606060408201525f82518060608401528060208501608085015e5f6080828501015260807fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe0601f83011684010191505094935050505056fea2646970667358221220a410641a09ba482816cc9ad191e93c5ffb6860613201a451fd134c38e579705b64736f6c634300081a0033";

type MultiReturnExampleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MultiReturnExampleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MultiReturnExample__factory extends ContractFactory {
  constructor(...args: MultiReturnExampleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MultiReturnExample & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MultiReturnExample__factory {
    return super.connect(runner) as MultiReturnExample__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MultiReturnExampleInterface {
    return new Interface(_abi) as MultiReturnExampleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MultiReturnExample {
    return new Contract(address, _abi, runner) as unknown as MultiReturnExample;
  }
}
