/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  UniqueCount,
  UniqueCountInterface,
} from "../../../contracts/PracticeJunior/UniqueCount";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "addUniqueValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getUniqueCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "uniqueValues",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061023c806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806325b002e01461004657806327b4f7d71461006b57806384fdb04e14610073575b600080fd5b61005961005436600461015f565b610088565b60405190815260200160405180910390f35b600054610059565b61008661008136600461015f565b6100a9565b005b6000818154811061009857600080fd5b600091825260209091200154905081565b60005b60005481101561012c5781600082815481106100ca576100ca610178565b90600052602060002001540361011a576040517f08c379a0000000000000000000000000000000000000000000000000000000008152602060048201526000602482015260440160405180910390fd5b80610124816101a7565b9150506100ac565b50600080546001810182559080527f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e5630155565b60006020828403121561017157600080fd5b5035919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fd5b60007fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff82036101ff577f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b506001019056fea26469706673582212200daf38d9819c1654bdb41650739ec96b1d7c1d49bc1eb0109a11e7853dec049d64736f6c63430008140033";

type UniqueCountConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UniqueCountConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UniqueCount__factory extends ContractFactory {
  constructor(...args: UniqueCountConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      UniqueCount & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): UniqueCount__factory {
    return super.connect(runner) as UniqueCount__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UniqueCountInterface {
    return new Interface(_abi) as UniqueCountInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): UniqueCount {
    return new Contract(address, _abi, runner) as unknown as UniqueCount;
  }
}
