/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionDenialOfServiceSol from "./AuctionDenialOfService.sol";
export type { auctionDenialOfServiceSol };
import type * as auctionReentrancySol from "./AuctionReentrancy.sol";
export type { auctionReentrancySol };
import type * as auctionTxOriginSol from "./AuctionTxOrigin.sol";
export type { auctionTxOriginSol };
import type * as bankHoneypotSol from "./BankHoneypot.sol";
export type { bankHoneypotSol };
import type * as gameCommitRevealSol from "./GameCommitReveal.sol";
export type { gameCommitRevealSol };
