/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionDenialOfServiceSol from "./AuctionDenialOfService.sol";
export type { auctionDenialOfServiceSol };
import type * as auctionReentrancySol from "./AuctionReentrancy.sol";
export type { auctionReentrancySol };
