/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  Mapping,
  MappingInterface,
} from "../../../../contracts/PracticeModule1/LessonMapping.sol/Mapping";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "get",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "myMap",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "remove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_i",
        type: "uint256",
      },
    ],
    name: "set",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101d2806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806327cbd5291461005157806329092d0e146100835780633825d828146100ba578063c2bc2efc146100f1575b600080fd5b61007161005f366004610150565b60006020819052908152604090205481565b60405190815260200160405180910390f35b6100b8610091366004610150565b73ffffffffffffffffffffffffffffffffffffffff16600090815260208190526040812055565b005b6100b86100c8366004610172565b73ffffffffffffffffffffffffffffffffffffffff909116600090815260208190526040902055565b6100716100ff366004610150565b73ffffffffffffffffffffffffffffffffffffffff1660009081526020819052604090205490565b803573ffffffffffffffffffffffffffffffffffffffff8116811461014b57600080fd5b919050565b60006020828403121561016257600080fd5b61016b82610127565b9392505050565b6000806040838503121561018557600080fd5b61018e83610127565b94602093909301359350505056fea264697066735822122024a448f4cb82f2833d8253158a4c5e04471f4e1e605bcc114f0eea4a2593e91564736f6c63430008140033";

type MappingConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MappingConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Mapping__factory extends ContractFactory {
  constructor(...args: MappingConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Mapping & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Mapping__factory {
    return super.connect(runner) as Mapping__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MappingInterface {
    return new Interface(_abi) as MappingInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Mapping {
    return new Contract(address, _abi, runner) as unknown as Mapping;
  }
}
