/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  NestedMapping,
  NestedMappingInterface,
} from "../../../../contracts/practice-module-1/LessonMapping.sol/NestedMapping";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr1",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_i",
        type: "uint256",
      },
    ],
    name: "get",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "nested",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr1",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_i",
        type: "uint256",
      },
    ],
    name: "remove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr1",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_i",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_boo",
        type: "bool",
      },
    ],
    name: "set",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f80fd5b5061022a8061001c5f395ff3fe608060405234801561000f575f80fd5b506004361061004a575f3560e01c80630b1391941461004e57806314bd0a7b1461009d578063abe7f1ab146100db578063b464631b14610120575b5f80fd5b61009b61005c36600461018b565b73ffffffffffffffffffffffffffffffffffffffff929092165f9081526020818152604080832093835292905220805460ff1916911515919091179055565b005b6100c76100ab3660046101cc565b5f60208181529281526040808220909352908152205460ff1681565b604051901515815260200160405180910390f35b61009b6100e93660046101cc565b73ffffffffffffffffffffffffffffffffffffffff9091165f9081526020818152604080832093835292905220805460ff19169055565b6100c761012e3660046101cc565b73ffffffffffffffffffffffffffffffffffffffff919091165f90815260208181526040808320938352929052205460ff1690565b803573ffffffffffffffffffffffffffffffffffffffff81168114610186575f80fd5b919050565b5f805f6060848603121561019d575f80fd5b6101a684610163565b925060208401359150604084013580151581146101c1575f80fd5b809150509250925092565b5f80604083850312156101dd575f80fd5b6101e683610163565b94602093909301359350505056fea2646970667358221220c82882ca60040e75168f6d803b6ce2e38335987087be7fab98d6f3602ecb05ad64736f6c634300081a0033";

type NestedMappingConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NestedMappingConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NestedMapping__factory extends ContractFactory {
  constructor(...args: NestedMappingConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      NestedMapping & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): NestedMapping__factory {
    return super.connect(runner) as NestedMapping__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NestedMappingInterface {
    return new Interface(_abi) as NestedMappingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NestedMapping {
    return new Contract(address, _abi, runner) as unknown as NestedMapping;
  }
}
